# typed: false
# frozen_string_literal: true

# This file is a local reference copy.
# The actual formula in hiromaily/homebrew-tap is auto-generated by GoReleaser
# on every release. Do not edit this file to change installation behavior —
# update .goreleaser.yaml instead.
#
# Tap repository: https://github.com/hiromaily/homebrew-tap
class DocsSsot < Formula
  desc "Documentation Single Source of Truth (SSOT) generator"
  homepage "https://github.com/hiromaily/docs-ssot"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hiromaily/docs-ssot/releases/download/v#{version}/docs-ssot_#{version}_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_SHA256"
    end

    on_arm do
      url "https://github.com/hiromaily/docs-ssot/releases/download/v#{version}/docs-ssot_#{version}_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_SHA256"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hiromaily/docs-ssot/releases/download/v#{version}/docs-ssot_#{version}_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_SHA256"
    end

    on_arm do
      url "https://github.com/hiromaily/docs-ssot/releases/download/v#{version}/docs-ssot_#{version}_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_SHA256"
    end
  end

  def install
    bin.install "docs-ssot"
  end

  test do
    system "#{bin}/docs-ssot", "version"
  end
end
